### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [22]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [23]:
array=np.zeros(10)
print("an array of 10 zeros:")
print(array)
array=np.ones(10)
print("an array of 10 ones:")
print(array)
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
an array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [24]:
array=np.arange(30,71)
print("array of the integers from 30 to70")
print(array)

array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [25]:
array=np.arange(10,50,2)
print("Array of even integers from 10 to 50")
print(array)

Array of even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [26]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### 5. Write a NumPy program to generate a random number between 0 and 1

In [28]:
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-0.14925029]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [29]:
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-1.57603557 -0.53572479 -0.49101282  1.14477494  0.01361866 -1.28373931
  0.43927646 -0.67227486 -1.74208079 -1.88137485 -0.78074121 -1.98667133
  0.82831519  0.51357861  0.23643136]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [30]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [31]:
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]
Vector-2
[ 5 10  9 10]
Multiply the values of two said vectors:
[ 5 80 27 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [32]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [33]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]




###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [34]:
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [35]:
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))


Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
